services:
  - docker

before_install:
  - docker build -t kalaxia/front . 

script:
  - docker run -it -e "NODE_ENV=test" -e "PORTAL_URL=https://www.kalaxia.com" -e "API_URL=http://kalaxia_nginx" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -e COVERALLS_REPO_TOKEN="$COVERALLS_REPO_TOKEN" kalaxia/front

deploy:
  - provider: script
    script: bash deploy/prod.sh
    on:
      tags: true
  - provider: script
    script: bash deploy/preprod.sh
    on:
      branch: develop
  
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
