services:
  - docker

before_install:
  - cp config.dist.js config.js
  - docker build -t kalaxia/front . 

script:
  - docker run -it -e "NODE_ENV=test" kalaxia/front npm run test-ci

deploy:
  - provider: script
    script: bash deploy/prod.sh
    on:
      tags: true
  - provider: script
    script: bash deploy/preprod.sh
    on:
      branch: develop
  
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL